#!/bin/bash

set -e

# # example /etc/backup.env
#
# # restic variables
# export RESTIC_REPOSITORY=
# export RESTIC_PASSWORD_FILE=
# export B2_ACCOUNT_ID=
# export B2_ACCOUNT_KEY=
#
# # config files
# export BACKUP_INCLUDE_FILE=/etc/backup.include
# export BACKUP_EXCLUDE_FILE=/etc/backup.exclude
# export BACKUP_RUNPARTS=/etc/backup.d/
#
[ -z "$BACKUP_CONFIG_FILE" ] && BACKUP_CONFIG_FILE="$HOME/.config/backup/backup.env"

init() {
	restic init
}

check() {
	restic check
}

forget() {
	restic forget \
	--keep-daily 7 \
	--keep-weekly 4 \
	--keep-monthly 12 \
	--keep-yearly 2 \
	--group-by host \
	--verbose \
	--prune
}

with_env() {
	exec $SHELL
}

restic_backup() {
	local backup_name="$1"

	restic backup \
	--verbose \
	--tag "${backup_name}" \
	--exclude-caches \
	--exclude '/home/*/.cache' \
	--exclude '/root/.cache' \
	--exclude-file "$BACKUP_EXCLUDE_FILE" \
	--files-from "$BACKUP_INCLUDE_FILE"
}

runparts() {
	local mode="$1"

	[ -d "$BACKUP_RUNPARTS" ] \
		&& run-parts -v --umask 077 --arg "$1" "$BACKUP_RUNPARTS"
}

backup() {
	local backup_name="$(hostname)-$(date -Id)"

	runparts pre || { echo "Runparts pre failed"; exit 1; }
	restic_backup || { echo "Backup failed"; exit 2; }
	runparts post || { echo "Runparts post failed"; exit 4; }
	forget || { echo "Forget failed"; exit 8; }
	check || { echo "Check failed"; exit 16; }
}

help() {
cat <<EOF
usage: ${0##*/} backup|check|forget|help|init|snapshots|with-env

    backup                        - Run backup
    check                         - Execute restic check
    forget                        - Prune repositry according to policy
    help                          - Print this help
    init                          - Init repository (if it does not already exist)
    snapshots                     - List repository snapshots
    with-env                      - start $SHELL with restic env-vars set
EOF
}

source "$BACKUP_CONFIG_FILE"
cmd=${1:-backup}

case "$cmd" in
	backup|check|forget|help|init|snapshots) "$cmd";;
	with-env) with_env;;
	*) help; exit 1;;
esac
