#!/bin/sh
#
# Example EASYPKG
#
#
# NAME=fancy-pants
# PKGVER=0.1.0
# PKGREL=1
# SOURCES=(ssh://github.com/fancy-pants/fancy-pants@bf6fbc7dba8)
#
# build() {
#     return
# }
#
# package() {
#     install -m 0755 -d "$D"/etc/example.d/
#     install -m 0600 "$S"/fancy-pants/README.md "$D"/etc/example.d/
# }

set -e

unset NAME PKGVER PKGREL SOURCES

. ./EASYPKG

mkdir -p src/
mkdir -p pkg/

export S="$(pwd)/src"
export D="$(pwd)/pkg"

for s in $SOURCES ; do
    src="$(echo "$s" | cut -d @ -f 1)"
    rev="$(echo "$s" | cut -d @ -f 2)"

    (
        cd src/
        git clone "$src" "$(basename "$src")"
        cd "$(basename "$src")"
        git checkout "$rev"
    )
done

if [ $(type -t build) = "function" ] ; then
    (build)
fi

if [ $(type -t package) = "function" ] ; then
    fakeroot -- /bin/sh -c ". ./EASYPKG; package"
fi

fakeroot -- tar -C pkg/ -cazf "${NAME}-${PKGVER}-${PKGREL}.tar.gz" --xform s:'./':: .
