#!/bin/sh
#
# Example EASYBUILD
#
#
# NAME=fancy-pants
# PKGVER=0.1.0
# PKGREL=1
# SOURCES=(ssh://github.com/fancy-pants/fancy-pants@bf6fbc7dba8)
#
# build() {
#     return
# }
#
# package() {
#     install -m 0755 -d "$D"/etc/example.d/
#     install -m 0600 "$S"/fancy-pants/README.md "$D"/etc/example.d/
# }

set -e

. ./EASYBUILD

mkdir -p src/
mkdir -p pkg/

for s in $SOURCES ; do
    src="$(echo "$s" | cut -d @ -f 1)"
    rev="$(echo "$s" | cut -d @ -f 2)"

    echo "Fetching $(basename "$src").."
    (
        cd src/
        git clone -q "$src" "$(basename "$src")"
        cd "$(basename "$src")"
        git checkout -q "$rev"
    )
done

if [ $(type -t build) = "function" ] ; then
    S="$(pwd)/src" build
fi

if [ $(type -t package) = "function" ] ; then
    S="$(pwd)/src" D="$(pwd)/pkg" fakeroot -- /bin/sh -c ". ./EASYBUILD; package"
fi

fakeroot -- tar -C pkg/ -czf "${NAME}-${PKGVER}-${PKGREL}.tar.gz" --xform s:'./':: .
