#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import requests
import sys

languages = ','.join(sys.argv[1:])

try:
    response = requests.get(f'https://gitignore.io/api/{languages}')
    if response.ok:
        print(response.text)

except IOError as e:
    print(e, file=sys.stderr)
