#!/bin/sh

# example metadata for markdown file:
#
# ---
# author: Maik
# title: Awesone presentation
#
# themeoptions:
#   - background=dark (light, dark)
#   - numbering=fraction (counter, none, fraction)

common_options="-t beamer -V theme:metropolis"

for f in "$@"
do
    pandoc $common_options -V aspectratio:43 -o $(basename -s .md "$f")-beamer-43.pdf "$f"
    pandoc $common_options -V aspectratio:169 -o $(basename -s .md "$f")-beamer-169.pdf "$f"
    pandoc $common_options -V aspectratio:1610 -o $(basename -s .md "$f")-beamer-1610.pdf "$f"
done
