#!/bin/sh

this_binary=${0##*/}

PO_URI="https://api.pushover.net/1/messages.json"
source ~/.config/pushover/pushover.env


usage() {
cat <<EOF
Usage: $this_binary [OPTIONS]

$this_binary sends a message via pushover.net

  Options:
    -h, --help      Print this help message.
    -t, --title     Message title (optional, defaults to \$(whoami)@\$(hostname))
    -b, --body      The message body (optional, defaults to stdin)
    -m, --monospace Print the message in monospace
EOF
}

opts=$(getopt -o ht:b:m -l help,title:,message:,body:,monospace -- "$@")
[ $? -eq 0 ] || { usage ; exit 1; }
eval set -- "$opts"

while true ; do
    case "$1" in
        --title|-t) title="$2";;
        --body|-b) body="$2";;
        --monospace|-m) mono=1;;
        --help|-h) usage; exit 0;;
        --) break;;
    esac
    shift
done

if [ -z "${body}" ] ; then
    body="$(cat)"
fi

if [ -z "${body}" ] ; then
    echo message body must not be empty
    usage
    exit 1
fi

curl --silent "${PO_URI}" \
    --form-string "user=${PO_USER}" \
    --form-string "token=${PO_TOKEN}" \
    --form-string "monospace=${mono:-0}" \
    --form-string "title=${title:-$(whoami)@$(hostname)}" \
    --form-string "message=${body}"
