#!/usr/bin/env python3

import re
import shutil
import sys
from collections import OrderedDict
from PIL import Image
from pillow_heif import register_heif_opener



REGEX = re.compile(r"(\d{4}):(\d{2}):(\d{2}) (\d{2}):(\d{2}):(\d{2})")


def get_exif_date(filename):
    image = Image.open(filename)
    image.verify()

    return image.getexif()[306]


def try_insert(dict, date, old_filename):
    year, month, day, hour, minute, second = date
    new_filename = f"{year}-{month}-{day}_{hour}-{minute}-{second}.heic"

    i = 0
    while new_filename in dict:
        new_filename = f"{year}-{month}-{day}_{hour}-{minute}-{second}_{i}.heic"
        i += 1

    dict[new_filename] = old_filename


if __name__ == "__main__":
    register_heif_opener()

    files = OrderedDict()

    for filename in sys.argv[1:]:
        date = get_exif_date(filename)

        if m := REGEX.match(date):
            try_insert(files, m.groups(), filename)


    for i, (new, old) in enumerate(files.items()):
        print(f"{i:6d} {old} -> {new}")
        shutil.move(old, new)
